Enhance versioning support
michael-simons/neo4j-migrations pull request #160
Opened 2021-01-28 09:24 UTC by katya-dovgalets

A partial solution for https://github.com/michael-simons/neo4j-migrations/issues/159

2021-01-28 09:34 UTC, michael-simons requested changes
That's a great PR, thank you!

I have only to complain what check style complains as well:
Please run `mvn checkstyle:check@validate` and fix the small number of things, please (mainly license header).

I will merge this and happily release it.

Wrt repeatable versions: Hardly at the moment
Wrt undoable: I have to think about it a bit.

2021-01-28 09:34 UTC, michael-simons commented on neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationVersion.java
> +	private static final String BASELINE_VALUE = "BASELINE";
Nice catch!! 👍

2021-01-29 14:37 UTC, michael-simons commented
Hm, why did you close it?

2021-01-29 16:40 UTC, katya-dovgalets commented
Reopened 
PR was closed automatically after force push in my branch.

2021-02-05 09:13 UTC, merged

2021-02-05 09:14 UTC, michael-simons commented
Thank you very much, Kateryna! Having a first contributor here makes me really happy.

2022-09-10 13:17 UTC, michael-simons commented
@all-contributors add @katya-dovgalets for code